In [1]:
import numpy as np

In [4]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.array([[2,2,2,2],[1,1,1,1]])

array([[2, 2, 2, 2],
       [1, 1, 1, 1]])

In [8]:
np.array([1,1,1,1])

array([1, 1, 1, 1])

In [9]:
mi_lista=[0,2,5.5,4,6,9]

In [10]:
np.array(mi_lista)

array([0. , 2. , 5.5, 4. , 6. , 9. ])

In [12]:
np.zeros(4).reshape(2,2)

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full(shape=(5,5),fill_value=10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [22]:
base=np.linspace(2,6,3)
base

array([2., 4., 6.])

In [23]:
np.full_like(base,np.pi)

array([3.14159265, 3.14159265, 3.14159265])

In [33]:
np.random.rand(4,4)

array([[0.30946652, 0.44673622, 0.43005605, 0.55229932],
       [0.71306343, 0.08065805, 0.139864  , 0.16962037],
       [0.71472347, 0.97569796, 0.31570785, 0.88952071],
       [0.3760428 , 0.5910449 , 0.57103455, 0.75220961]])

In [48]:
np.random.uniform(low=1,high=2,size=5)

array([1.50708672, 1.47700332, 1.93340061, 1.5238872 , 1.69427776])

In [57]:
np.random.randn(2,2)

array([[0.68219939, 0.72092002],
       [1.21466359, 0.44331548]])

In [59]:
np.random.normal(loc=5,scale=2,size=10)

array([5.666041  , 5.01987478, 5.30058935, 3.59081985, 7.45937086,
       4.69209028, 3.54988317, 6.74281899, 4.75414173, 2.02577535])

In [60]:
mi_lista2=[[2,2,2],[3,1,2],[2,2,1]]
np.array(mi_lista2)

array([[2, 2, 2],
       [3, 1, 2],
       [2, 2, 1]])

In [61]:
np.random.randint(low=0,high=10,size=10)

array([2, 5, 1, 8, 3, 1, 1, 7, 7, 9])

In [62]:
A=np.arange(8).reshape(2,2,2)
B=np.ones(8).reshape(2,2,2)

In [63]:
A,B

(array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]]))

In [64]:
A+B

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [65]:
A-B

array([[[-1.,  0.],
        [ 1.,  2.]],

       [[ 3.,  4.],
        [ 5.,  6.]]])

In [68]:
matriz_a=np.mat(([2,2],[2,3]))

In [69]:
#inversa
matriz_a.I

matrix([[ 1.5, -1. ],
        [-1. ,  1. ]])

In [70]:
np.mean([2,3,2,2])

2.25

In [71]:
np.std([1,2,3,4,5,64])

22.76998511686431

In [82]:
np.exp(np.e),np.log(10),np.sqrt(10)

(15.154262241479262, 2.302585092994046, 3.1622776601683795)

In [ ]:
# np.asmatrix() , np.asarray()


In [83]:
%%timeit
a=np.arange(1000)
b=np.ones(1000)
a+b

5.48 µs ± 66.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [84]:
%%timeit
a=np.arange(1000)
b=np.zeros(1000)
i=0
for j in a:
    b[i]=j+j
    i+=1

275 µs ± 1.75 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [87]:
type(np.nan)
np.nan

nan

In [88]:
mi_array_3=np.arange(0,10).reshape(2,5)
print(mi_array_3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [91]:
filtro=((mi_array_3 % 2))==0

In [92]:
filtro

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [93]:
mi_array_3[filtro]

array([0, 2, 4, 6, 8])