In [61]:
import numpy as np
#Operaciones que se pueden realizar en un arreglo de Numpy y en listas:

In [62]:
#arreglo apartir de lista

lista=[1,2,3,4,5,6]
arreglo=np.array(lista)
print(lista)
print(arreglo)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [63]:
#modo Numpy
arreglo=np.arange(8)
print(arreglo)
print(type(arreglo))

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [64]:
#Operaciones que se pueden hacer con Numpy pero no con listas:
lista+1

TypeError: can only concatenate list (not "int") to list

In [ ]:
#sumarle un elemento
arreglo+2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
#elevarlo al cuadrado los elementos
arreglo**2

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
#sumar todos los elementos
print(arreglo.sum())
print(lista.sum())

28


AttributeError: 'list' object has no attribute 'sum'

In [ ]:
#en caso de la lista
n=0
for e in lista:
    n=n+e
print(n)

21


In [ ]:
#ver las dimensiones del arreglo
arreglo.shape

(8,)

In [ ]:
arreglo=np.array([[2,3,4],[2,5,6],[5,6,7]])
print(f"el arreglo \n {arreglo} \n tiene dimesiones {arreglo.shape}")

el arreglo 
 [[2 3 4]
 [2 5 6]
 [5 6 7]] 
 tiene dimesiones (3, 3)


In [ ]:
#cual es la diferencia entre un arreglo de forma -shape- (n,),(n,1) y (1,n)
print("arreglo de (n,)")
arreglo=np.array([1,2,3,4,5])
print(arreglo,arreglo.shape)

print("arreglo de (n,1)")
arreglo=np.array([[1,2,3,4,5]])
print(arreglo.T,arreglo.T.shape)

print("arreglo de (2,n) ")
arreglo=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arreglo,arreglo.shape)

arreglo de (n,)
[1 2 3 4 5] (5,)
arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)
arreglo de (2,n) 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] (2, 6)


In [ ]:
#Transponer no es la unica forma de crear un arreglo n,1
arreglo=np.array([[1],[2],[3],[4],[5]])
print(arreglo,arreglo.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


Escribir un arreglo con numeros enteros del 0 al 9.Pista arange

In [ ]:
arreglo=np.arange(10)
print(arreglo)

[0 1 2 3 4 5 6 7 8 9]


Escribir un arreglo con 100 numeros equiespaciados del 0 al 9.Pista linspace

In [ ]:
arreglo=np.linspace(start=0,stop=9,num=100)
print(arreglo)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

Escribir un arreglo con numeros enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3. Pista mask

In [ ]:
arreglo=np.arange(start=10,stop=101)
print(arreglo)

filtro=arreglo%3 == 0
print(filtro)
arreglo[filtro]

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False]


array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Crear un arreglo de ceros de shape (5,10)


In [ ]:
arreglo=np.zeros(shape=(5,10))
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Reemplazar la segunda y cuarta fila con unos

In [ ]:
arreglo[1]=arreglo[1]+1
arreglo[3]=arreglo[3]+1
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Reemplazar la tercera y la octava columna con dos

In [ ]:
arreglo[:,2]=2
arreglo[:,7]=2
print(arreglo)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


In [ ]:
arreglo2=np.ones((3,3))
print(arreglo2)
arreglo2[1,:]=0
print(arreglo2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [0. 0. 0.]
 [1. 1. 1.]]


Create a 1D array of numbers from 0 to 9

In [ ]:
arreglox=np.array([0,1,2,3,4,5,6,7,8,9])
print(arreglox)
print(arreglo.shape)
arreglox2=np.arange(start=0,stop=10,step=1)
print(arreglox2)
print(arreglox2.shape)

[0 1 2 3 4 5 6 7 8 9]
(5, 10)
[0 1 2 3 4 5 6 7 8 9]
(10,)


Create a 3×3 numpy array of all True’s

In [ ]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
filtro=arr%2!=0
print(arr[filtro])

[1 3 5 7 9]


Replace all odd numbers in arr with -1

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2!=0] =-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


 Replace all odd numbers in arr with -1 without changing arr

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar2=arr.copy()
ar2[ar2%2!=0]=-1
print(arr)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Convert a 1D array to a 2D array with 2 rows

In [ ]:
np.arange(10).reshape((2,-1))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Stack arrays a and b vertically

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("primer metodo")
print(np.concatenate([a,b],axis=0))

print("\nsegundo metodo ")
print(np.vstack([a,b]))

print("\n tercer metodo")
print(np.r_[a,b])


primer metodo
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

segundo metodo 
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

 tercer metodo
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Stack the arrays a and b horizontally.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print("metodo1")
print(np.concatenate([a,b],axis=1))

print("\nmetodo2")
print(np.hstack([a,b]))

print("\nmetodo3")
print(np.c_[a,b])


metodo1
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

metodo2
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

metodo3
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Create the following pattern without hardcoding. Use only numpy functions and the below input array

In [ ]:
a = np.array([1,2,3])

b=np.concatenate([np.repeat(a=a,repeats=3),np.tile(A=a,reps=3)])

print(b)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


 Get the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(ar1=a,ar2=b)
print(c)

[2 4]


 How to remove from one array those items that exist in another?

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c=np.setdiff1d(ar1=a,ar2=b)
print(c)

[1 2 3 4]


. Get the positions where elements of a and b match

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
print(c)


(array([1, 3, 5, 7], dtype=int64),)


Get all items between 5 and 10 from a

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
#(array([6, 9, 10]),)
b=a[(a>=5) & (a<=10)]
#devuelve bool
print(b)

#metodo2

index=np.where((a>=5)& (a<=10))
#devuelve indice
print (a[index])

#metodo3

index=np.where(np.logical_and(a>=5,a<=10))
#devuelve indice
print(a[index])



[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


Convert the function maxx that works on two scalars, to work on two arrays

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [ ]:
#Retorna indice mas alto de ambos arrays
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def pair_maxx(x,y):
    max1=np.max(a=a)
    max2=np.max(a=b)
    if max1>= max2:
        return max1
    else:
        return max2
pair_maxx(a, b)

9

In [ ]:
#Recorre ambos arrays devolviendo un nuevo array que contiene los mas grandes de cada posicion
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x,y):
    if x>=y:
        return x
    else:
        return y

pair_maxx=np.vectorize(maxx,otypes=[float])

pair_maxx(a,b)

array([6, 7, 9, 8, 9, 7, 5])

 Swap columns 1 and 2 in the array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr,"\n")
arr[:,[1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Swap rows 1 and 2 in the array arr:

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr,"\n")

arr[[0,2,1],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

Reverse the rows of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr,"\n")
#metodo1
arr[[2,1,0]]
#metodo2
arr[::-1]


[[0 1 2]
 [3 4 5]
 [6 7 8]] 



array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Reverse the columns of a 2D array arr

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
print("\n",arr[:,::-1])
print("\n",arr[:,[2,1,0]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[2 1 0]
 [5 4 3]
 [8 7 6]]

 [[2 1 0]
 [5 4 3]
 [8 7 6]]


Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [ ]:
np.full(shape=(5,3),fill_value=(np.random.randint(low=5,high=10)))

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
arr=np.arange(9).reshape(3,3)
arr
rand_arr=np.random.randint(low=5,high=10,size=(5,3))+ np.random.random((5,3))
print(rand_arr)


arr=np.arange(9).reshape(3,3)
arr
rand_arr2=np.random.randint(low=5,high=10,size=(5,3)) #si queremos enteros
print(rand_arr2)




[[7.70244864 7.28321032 7.4139229 ]
 [7.9929872  6.03128156 6.38834599]
 [5.59085157 7.41334253 8.65221142]
 [8.34934166 6.3944714  5.3965517 ]
 [5.44188435 9.53755444 8.63314347]]
[[9 6 7]
 [6 6 6]
 [9 6 8]
 [5 6 9]
 [6 8 7]]


In [ ]:
#metodo 2
rand_arr=np.random.uniform(5,10,size=(5,3))
print(rand_arr)

[[5.1288488  8.51510651 7.52081063]
 [7.2769504  9.58948701 6.172147  ]
 [5.79247292 7.86604428 5.1045759 ]
 [5.90864258 9.02172198 6.62915437]
 [5.66326188 7.58125536 7.11201954]]


Print or show only 3 decimal places of the numpy array rand_arr

In [ ]:
rand_arr = np.random.random((5,3))
rand_arr
np.set_printoptions(precision=3)
print(rand_arr)


[[0.204 0.255 0.574]
 [0.523 0.303 0.972]
 [0.165 0.727 0.334]
 [0.323 0.651 0.616]
 [0.795 0.571 0.372]]


 Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [ ]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True,precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [ ]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Print the full numpy array a without truncating.

In [ ]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=sys.maxsize)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Import the iris dataset keeping the text intact

In [ ]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris=np.genfromtxt(url,delimiter=",",dtype='object')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

Extract the text column species from the 1D iris imported in previous question.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

C:\Users\gomez\AppData\Local\Temp\ipykernel_14700\3338009947.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


In [ ]:

species=np.array([row[4] for row in iris_1d])
species


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [73]:
%%timeit
a=np.arange(200,dtype=np.int16)
a

693 ns ± 4.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [74]:
%%timeit
a=np.arange(200,dtype=np.int64)

694 ns ± 6.13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
